import { StockItem, Store } from "./lib/schema/inventory";
import { uniqueId } from "./lib/utils";
import { AddOn, MenuItem, PairedItem } from "./types/menu";

export const demoAddOns: AddOn[] = [
  {
    id: uniqueId(),
    name: "Plantain",
    price: 500,
    image: "/images/food/plantain.jpg",
  },
  {
    id: uniqueId(),
    name: "ColeSlaw",
    price: 1000,
    image: "/images/food/coleslaw.jpeg",
  },
];

export const demoPairedItems: PairedItem[] = [
  {
    id: uniqueId(),
    name: "Pepsi",
    price: 400,
    image: "/images/food/pepsi.jpg",
  },
  {
    id: uniqueId(),
    name: "Coke",
    price: 450,
    image: "/images/food/coke.jpg",
  },
];

export const demoMenuItems: MenuItem[] = [
  {
    id: uniqueId(),
    price: 1000,
    name: "Jollof Rice",
    category: "Rice Dishes",
    status: "available",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-1.png",
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "Fried Rice",
    price: 1200,
    category: "Rice Dishes",
    status: "unlisted",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-2.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "Grilled Fish with Fried Plantain",
    price: 2500,
    category: "Grills & BBQ",
    status: "available",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-3.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "BBQ Chicken Thighs",
    price: 2000,
    category: "Grills & BBQ",
    status: "unlisted",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-4.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
  {
    id: uniqueId(),
    name: "BBQ Chicken Drumsticks",
    price: 1500,
    category: "Grills & BBQ",
    status: "available",
    readyTime: { hours: 0, minutes: 10 },
    image: "/images/food/food-5.png",
    portions: 2,
    ingredients: "...",
    size: { amount: 1, unit: "kg" },
    pairedItems: [demoPairedItems[0].id, demoPairedItems[1].id],
    addOns: [demoAddOns[0].id, demoAddOns[1].id],
  },
];

export const demoStores: Store[] = [
  {
    id: "default",
    name: "Stores",
    description: "Default store created by the system",
    image: "/images/store/store-1.png",
  },
  {
    id: "chicken-hotspot",
    name: "Chicken Hotspot",
    description: "Your go-to spot for chicken and frozen foods",
    image: "/images/store/store-2.png",
  },
];

export const demoStockItems: StockItem[] = [
  {
    id: uniqueId(),
    name: "Frozen Chicken Wings",
    store: demoStores[1].id,
    image: "/images/store/chicken-wings.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Drumsticks",
    store: demoStores[1].id,
    image: "/images/store/chicken-drumsticks.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Thighs",
    store: demoStores[1].id,
    image: "/images/store/chicken-thighs.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
  {
    id: uniqueId(),
    name: "Frozen Chicken Breast",
    store: demoStores[1].id,
    image: "/images/store/chicken-breast.png",
    expirationDate: { month: 12, year: 2025 },
    measuringUnit: "kg",
    lowStockThreshold: 5,
    category: "Frozen Foods",
    purchasePrice: 1500,
    quantity: 10,
  },
];
