on:
  workflow_dispatch:
  push:    
    branches:
      - uat
name: 🚀 Deploy Cook
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:        
        server: ftp.meergeafrica.com
        username: osher@food.meergeafrica.com
        password: ${{ secrets.pass }}
        local-dir: build/
