on:
  workflow_dispatch:
  push:    
    branches:
      - uat
name: 🚀 Deploy Cook
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:        
        server: ftp.meergeafrica.com
        username: osher@food.meergeafrica.com
        password: ${{ secrets.pass }}
